from __future__ import annotations

from typing import List, Optional, Protocol

from .booking import Booking
from .room import Room
from .value_objects import BookingId, RoomId


class RoomRepository(Protocol):
    def get(self, room_id: RoomId) -> Optional[Room]: ...
    def add(self, room: Room) -> None: ...


class BookingRepository(Protocol):
    def get(self, booking_id: BookingId) -> Optional[Booking]: ...
    def save(self, booking: Booking) -> None: ...
    def add(self, booking: Booking) -> None: ...
    def find_active_by_room(self, room_id: RoomId) -> List[Booking]: ...